### PR TITLE
Adds offline support

### PR DESCRIPTION
**Pull request by courtneypattison**
Needs some love and testing but the basics are here for #10.

### CODE REVIEW

**Comment by courtneypattison** [comment]
I'm happy enough with this one for now. It doesn't cache the gif from the first page and only caches the pages that you visit while online. There's definitely room for improvement but as long as this doesn't break anything I think it's better than no offline support. Thoughts?

**Comment by hluedeke** [comment]
> I'm happy enough with this one for now. It doesn't cache the gif from the first page and only caches the pages that you visit while online. There's definitely room for improvement but as long as this doesn't break anything I think it's better than no offline support. Thoughts?

Sure 👍 I have learned that a simple download button was far more complicated than I expected and that not all platforms support PWA's (the concept seems to be a bit fringe). I don't know much about PWA's, but any support is probably better than none 🤷‍♀️

**Comment by courtneypattison** [comment]
Lol, yeah, they definitely are fringe and may not be around that much longer! The way I've added offline support is with a service worker, so even if the site isn't "downloaded" it will be available offline in the browser, so going to https://www.patternprojector.com/ will still work when the device is offline.

**Comment by hluedeke** [comment]
> Lol, yeah, they definitely are fringe and may not be around that much longer! The way I've added offline support is with a service worker, so even if the site isn't "downloaded" it will be available offline in the browser, so going to https://www.patternprojector.com/ will still work when the device is offline.

That works for me! I also want to throw out that maybe having a separate url for /calibrate and /project should consider your service worker implementation. It might be better to have fewer urls if you need to visit them all to have offline support (maybe you could implement the project page with a query variable instead, like: /calibrate?project=true or something like that)

**Comment by courtneypattison** [comment]
> That works for me! I also want to throw out that maybe having a separate url for /calibrate and /project should consider your service worker implementation. It might be better to have fewer urls if you need to visit them all to have offline support (maybe you could implement the project page with a query variable instead, like: /calibrate?project=true or something like that)

Totally forgot to consider that issue! Good idea. Alternatively, it's possible to set up the service worker to precache specific pages, but I haven't learned how to do that yet!

**Pull request merged**
