### PR TITLE
Resolves #28. Toggles between points on tab. Adds 4-corner mode, with icon button (shift+click also toggles 4-corner mode)

### LINKED ISSUE #28: Tab through corners
Be able to tab through the calibration corners. A nice little power user extra?

### PR DESCRIPTION
**Pull request by hluedeke**

### CODE REVIEW

**Comment by hluedeke** [comment]
...I did not think about this...how are we handling internationalization on code changes? I think the aria-labels for the new toggle button are wrong, but I don't know how we should add new items. Everything in english to start? Or wait until we have translations?

**Comment by courtneypattison** [comment]
Hmm, once I get weblate hooked up, I think just changes to en makes sense so lets stick with that for now. What do you think about setting the default pointToModify to the top left and default show the corners. I think it would provide more affordance that the grid is moveable. I pulled this PR and made the changes to a hluedeke branch. I'm not sure what the best method is for adding edits. Should I just comment?

**Comment by hluedeke** [comment]
Yes, I'm good with that. I had the thought that the new mode might be better off as the default, but I wasn't confident in that. If you think so too, then yes! Let's do it!

I like the default pointToModify - sure! Why not?

The hluedeke branch should effectively be a clone of the main branch, so I'd just make edits as you see fit. In theory, and commits you push upstream should just show up here in the PR. Is that what you are asking?

**Comment by courtneypattison** [comment]
I ended up making a new branch by fetching this one with `git fetch origin pull/ID/head:BRANCH_NAME` so my changes aren't being reflected here. They're in a new branch.

**Comment by hluedeke** [comment]
Ok, I think I see what you were saying before now. You were just wanting to comment on the changes and have me implement them? Sorry, I am dense sometimes!

I'm glad you figured it out, and sorry for making that harder than it needed to be! I wasn't really understanding the problem, and I think it's because the hluedeke branch doesn't exist on your project - is that right?

**Comment by courtneypattison** [comment]
Please don't apologize! I'm just confused about how to have my changes reflected here. I think I just need to push my changes to a different origin instead of making a new branch. I wasn't sure if you'd rather I don't mess with your branches! I made a copy this morning and modified before messaging. I'll push that one and try again with the next PR, so yes please close this one.

**Comment by courtneypattison** [comment]
Wait, I think maybe my changes are here! Hold off for a bit.

**Comment by hluedeke** [comment]
Haha, ok. I wouldn't know how to do updates to a forked merge either 🤷‍♀️

**Comment by courtneypattison** [comment]
Lol, I'm just going to go for it. It looks like my commits aren't showing up on this page but are reflected in the preview. I guess we'll see.

**Pull request merged**
