### PR TITLE
Add line weight option to menu

### PR DESCRIPTION
**Pull request by courtneypattison**

### CODE REVIEW

**Comment by courtneypattison** [comment]
I've been using PP quite a bit over the last few days and started to get quite annoyed with the line weight, so I couldn't help but revisit this one. Here's the [preview](https://pattern-projector-git-thickness-courtney-pattisons-projects.vercel.app?_vercel_share=mU5HNk1iHFcpT2EPPNZ0KRptjC9aJrVN)!

**Comment by hluedeke** [comment]
K, I want to see this one, haha. I’m so impressed that you found a way to solve this one! I tried 2 or 3 different methods, and all were either too complicated or were resource intensive. So I’m really looking forward to checking this one out!

Did you find the line weights too thin or too thick out of curiosity?

**Comment by courtneypattison** [comment]
This one was my husband's idea! He's like, why not just use erode or dilate? I used copilot for help on this one.

**Comment by courtneypattison** [comment]
Ahh, I hope you feel better soon! Please don't feel like you have to work on this!

**Comment by hluedeke** [comment]
Thanks, I am enjoying it when I do have the time! I'm just letting you know that I'm probably not the best person to code review/preview changes at the moment, unless you're willing to wait a few days 😉 I certainly don't want to slow the momentum you have going right now!

**Comment by hluedeke** [comment]
This works really well and seems to be relatively performant as well - nice going!

**Comment by courtneypattison** [comment]
Woot woot! Thank you :)

**Pull request merged**
