### PR TITLE
Less reset center

### PR DESCRIPTION
**Pull request by j-huff**
fix for #150

### CODE REVIEW

**Comment by courtneypattison** [comment]
This is definitely better, but it still feels like a downgrade from how the stitch menu works on the main branch. I started refactoring the geometry library to see what I can do about this issue. I don't have anything ready enough to share yet though!

**Comment by j-huff** [comment]
I don't understand. What exactly is different?

**Comment by j-huff** [comment]
@courtneypattison I can tell you that whatever issue you are experiencing, it is most likely not due to the geometry library.

It is extremely difficult to have the following features co-exist:
- Align to the left on long document load, align to center if the document fits in the grid
- Document transform matrix is relative to the recenter of the document

Basically, it's difficult to trigger the recenter function once a new document is loaded but only once the layout states are completely finished being set. I was able to get away away with the left alignment by just calling resetTransformMatrix any time the layoutWidth or layoutHeight changed.

So possible solutions are:

- stop trying to align the PDF to the left on load
- make the document transform matrix origin be the upper left of the pdf (extremely annoying to do matrix operations if we go this route)
- Figure out a way of triggering the resetTransformMatrix after layoutWidth and layoutHeight has finished being updated ONLY by a new document being loaded. This one seems simple on the surface but is actually difficult. Maybe not impossible though?


Take your pick I guess.

**Comment by j-huff** [comment]
> Figure out a way of triggering the resetTransformMatrix after layoutWidth and layoutHeight has finished being updated ONLY by a new document being loaded. 

Went with this option.

**Comment by j-huff** [comment]
Well nevermind I guess I broke it again.

**Comment by j-huff** [comment]
okay I'm pretty sure it's actually fixed now 😅

**Comment by courtneypattison** [comment]
I made a PR #158 for moving the origin to the top left!

**Comment by j-huff** [comment]
> I made a PR #158 for moving the origin to the top left!

I didn't realize this was desirable. I purposefully moved the origin to center.

**Comment by j-huff** [comment]
I see. Makes sense to me.

**Pull request closed without merging**
