### PR TITLE
Add measuring

### PR DESCRIPTION
**Pull request by courtneypattison**
Adds some of #70 I still need to add key handlers and constraining to angles.

### CODE REVIEW

**Comment by courtneypattison** [comment]
I think I've added all the suggested functionality except hotkey toggling. I'm not sure where we want to put that. @hluedeke Do you have any suggestions for where we should put the all the hotkeys for the menubar? I believe you suggested before putting it in one place.

**Comment by hluedeke** [comment]
I think we should have a keydownlistener (or keyuplistener, pick your poison) and use a react hook to define it. That way we minimize the number of places that keydown handlers are called. The implementation would be very similar to the arrow key progressive handlers, where the handler is called in the hook, but the callback is accessible from anywhere that uses the hook.

The benefits here are a single keydown handler in the project on the window, and *hopefully down the line, simplification of troubleshooting collisions on key press, as key management is handled from a single place. The hook returns a callback, and the callback can be used anywhere in the project that we need key management.

**Comment by courtneypattison** [comment]
I tried to add what you described. Please let know if I've understood you correctly! Also, thoughts on this PR? Is it ready for beta?

**Comment by hluedeke** [comment]
> I tried to add what you described. Please let know if I've understood you correctly! Also, thoughts on this PR? Is it ready for beta?

Yes! We'll probably want to roll in the existing arrow key handlers to use the same callback at some point, but at least everything is in the same area of code at this point. Calling document-level handlers from nested components can be a nightmare when the component hierarchy gets complicated enough. I think this looks great! (I haven't run it yet in preview) I look forward to trying it!

**Comment by courtneypattison** [comment]
Awesome :) I'm quite happy with the useKeyDown hook. I think that was a great idea. We're slowly cleaning things up!

**Comment by hluedeke** [comment]
> Awesome :) I'm quite happy with the useKeyDown hook

Yeah! Looks great! This might seem like an unnecessary abstraction, but when you are troubleshooting things, the ability to lookup hook usages and clearly/cleanly read them will be very helpful I think. And I think we plan to introduce a lot more hotkeys, so getting this organized up front is a good idea!

**Comment by hluedeke** [comment]
Looks good!

**Comment by courtneypattison** [comment]
Now just merge conflicts lol!

**Pull request merged**
