### PR TITLE
Overlay mode selection + Hide Cursor Timer

### PR DESCRIPTION
**Pull request by j-huff**
Just combining the overlay with the previous pull request, apologies for my laziness 😅

Changes:
- Overlay can now be selected using the new component DropdownIconButton. This replaces the gridOn/gridOff button. Fixes issue #63 
- Canvas drawing code has been reorganized for better readability
- Solution for issue https://github.com/Pattern-Projector/pattern-projector/issues/78 . Cursor gets hidden after 1.5 seconds idle on the projection page.
- Also fixed a small bug with the color of the grid lines in calibration-canvas when in project light mode.

Todo:
- add translations
  - ~~English~~
- add more overlays
  - ~~paper sheet~~
- ~~remove commented out code (oops)~~

### CODE REVIEW

**Comment by j-huff** [comment]
For the sanity check overlay, I'm thinking of making it the border + a rectangle in the center that is the size of letter paper (8.5 x 11in). Could also add an option A4 paper, or just make the paper size dependent on if you are using imperial or metric for the grid. Unless there's people out there than would have a cutting mat in inches but use metric paper, or vice versa.

**Comment by courtneypattison** [comment]
> For the sanity check overlay, I'm thinking of making it the border + a rectangle in the center that is the size of letter paper (8.5 x 11in). Could also add an option A4 paper, or just make the paper size dependent on if you are using imperial or metric for the grid. Unless there's people out there than would have a cutting mat in inches but use metric paper, or vice versa.
> 

I think letter for inches and a4 for centimetres would work for most cases. I really like the idea of using paper for this!

> Edit: do we want to keep the feature where the overlayed is disabled if you open a PDF? I feel like with this update we should get rid of that and maybe just change the default overlay to "Border".

I agree. I think it'll be more obvious what it's for now and people can turn it off if they want. 

Also, didn't you mention not being that comfortable with front end stuff? You seem like a front end master. This PR is gorgeous. Thank you!

**Comment by j-huff** [comment]
> Also, didn't you mention not being that comfortable with front end stuff?

To be honest, I've been getting a lot of help from ChatGPT and claude.ai. Makes learning stuff much easier when you have the freedom to ask very specific and (sometimes) very dumb questions. Also maybe in the past I just didn't have the patience to have a better understanding of how React works. Contributing to someone else's project also helps to improve my code quality 😅 Glad you like it, I've certainly been having fun with it.

**Comment by courtneypattison** [comment]
I feel you with the ai help. I just got copilot a couple of weeks ago and I love it!

**Pull request merged**
