### PR TITLE
Disable pdf links

### PR DESCRIPTION
**Pull request by hluedeke**
## Pull Request Checklist

- [x] I have run `yarn build` to ensure that the project builds successfully.
- [x] I have updated `CHANGELOG.md` with the necessary changes made in this pull request.

## Description

Disables PDF links by disabling rendering of the PDF annotation layer. This was (roughly) the recommendation from PDFjs itself (https://github.com/mozilla/pdf.js/issues/10664). All relevant pattern data *should* be in the content layer, however, if we are having issues with disabling the annotation layer, we can always try a custom css option (if we have a way to implement custom css)

### CODE REVIEW

**Comment by courtneypattison** [comment]
Ooo, lovely to see your PR @hluedeke!

I had turned off the annotation layer when we were having size issues in the first week or two after the release. Then a couple of months ago someone was complained that they couldn't see their annotations in PP--they put many notes in their patterns--so I turned it back on.

Now I feel conflicted! What do you think?

**Comment by hluedeke** [comment]
Hi! I know! Feels good to be back! 😄

If the annotation layer is important, than we can try the custom css route. I just need a way to define custom css in the project (aka create our own css classes). Do we have a place to do this?

**Comment by courtneypattison** [comment]
> If the annotation layer is important, than we can try the custom css route. I just need a way to define custom css in the project (aka create our own css classes). Do we have a place to do this?

There's `app/[locale]/globals.css` that you can throw custom css classes in: [how to from tailwind!](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer)

**Comment by courtneypattison** [comment]
Perfect, thank you @hluedeke!

**Pull request merged**
