### PR TITLE
Converts CustomRenderer back to a Class in pdf-viewer. Passes layers/…

### PR DESCRIPTION
**Pull request by hluedeke**
…setLayers down through context instead. This fixes the flickering for me.

### CODE REVIEW

**Comment by courtneypattison** [comment]
I've never seen this done before! I need to work on my React knowledge! I just memoized the callback like you suggested and I think that works as well. I don't know enough about React to decide which one makes more sense if they both work.

**Comment by hluedeke** [comment]
They probably both work. I can test the memoized version if that’s easier to read for you and we can commit that version. This is using react context, which is basically a fancy way to pass props from an ancestor component to any of its descendants. It’s really cool when you need to pass the same props to large parts of the application (for example, you can pass a variable from the url or a themeing object all the way down your component tree without passing it as an arg to each component).

You’ll notice react-pdf uses it as well with getPageContext().

**Comment by courtneypattison** [comment]
Ah, that's cool. Good to know!

**Comment by courtneypattison** [comment]
Closing since useCallback seems to fix this issue and it's already in the layers branch.

**Pull request closed without merging**
