### PR TITLE
Initial commit (see description)

### PR DESCRIPTION
**Pull request by hluedeke**
- Adds in/cm support
- Adds the ability to pan the calibration grid in "calibration" mode
- Moves buttons and inputs to a permanent toolbar
- Adds a border to the PDF page for easier location on the page
- Saves height/width and in/cm preferences to localStorage

### CODE REVIEW

**Comment by courtneypattison** [comment]
@hluedeke OMG! You did so much! This looks amazing. Thank you so much. I need to get to sleep so I'll work on merging and maybe making a tiny change or two tomorrow.

**Comment by hluedeke** [comment]
Thank you! I know it's a lot for a single PR - I hope I didn't overwhelm you. I totally got sucked in! It's a nice change of pace to work on a simple, straightforward "baby" project again. I thoroughly enjoyed it!

**Comment by courtneypattison** [comment]
@hluedeke I shouldn't have looked at it right before bed. I was so excited about it, I had a hard time sleeping! The one thing that I'm really not sure what to do with is the back arrow. I originally had that same arrow, but my husband kept clicking it thinking it would take him back to the calibration or projection mode. I don't think changing it to an x helped at all because a couple people have mentioned that the x-ed out not understanding. Do you think maybe putting an icon sized version of the logo or just a home link there would make sense? I'm not sure what to do.

**Comment by hluedeke** [comment]
This one's tough, because what is "home"? Technically your landing page is home, but I think 99% of people will treat the calibration/projection page as home.

What if you did a button (not in the top left corner) with a help icon? Since that's where you put all your documentation? Just an idea!

I support the idea of a logo, but I think people would also click that and accidentally go back, and we'd be right back to where we started! If I saw a logo at the top, I would probably assume it meant "restart" or "reset", similar to what your trash can icon does today.

**Comment by hluedeke** [comment]
> @hluedeke I shouldn't have looked at it right before bed. I was so excited about it, I had a hard time sleeping!

Yes, so exciting! I'll do my best to be available over the next few weeks to help with issues, if you'd like. My life is about to start getting crazy here in the next few months, but I have a little breathing room before that all starts! Feel free to tag me on issues if you want a little extra manpower on things. I'm happy to help!

**Comment by hluedeke** [comment]
> @hluedeke Such a good idea! What about an info icon to the right of the calibrate/project button?

Let's try it!

**Pull request merged**
