### PR TITLE
Matrix based transforms

### PR DESCRIPTION
**Pull request by j-huff**
Hear me out...

In my opinion, all transformations applied to the PDF by tools (like rotate, flip, etc) should be applied to a single transformation matrix. The downside of this is that you are unable to completely disambiguate the transforms that are being applied to the PDF. This means you cannot determine things like its absolute mirror state (I could be mistaken about this, but from my testing it doesn't work). I've change the two state mirror buttons to single state. You *can* still determine things like it's position, rotation, and scale from the matrix.

This have a lot of benefits:
- Calculating the final transform is simple. Adding more tools doesn't change the calculation.
- Rotation button works as expected. Before, the pattern would be rotated anti-clockwise if it was mirrored.
- Adding more transformation tools will be much easier.
- If we implement history we most likely only need to track a single matrix

The TransformSettings.matrix is in unitsOfMeasure. This should make it straightforward to apply exact translations to it for future tools like grid snapping and "translate by".

A nice little bonus of this implementation is that the position of the PDF doesn't get reset if the calibration is modified, and recentering works properly now (it was a little off before).

Let me know what you think of this change.

### CODE REVIEW

**Comment by j-huff** [comment]
Adding the "mirror about line" tool we were discussing in #124 will be much easier with change.

**Comment by courtneypattison** [comment]
I agree! I've been thinking about switching to a single matrix with transformations for a while. Thank you!

**Comment by j-huff** [comment]
No, this shouldn't change anything about the calibration. The only major thing that has been changed is TransformSettings, which only gets applied to the position of the PDF. TransformSettings does get loaded from local storage, but from my understanding my modification shouldn't cause an error when migrating.

**Comment by hluedeke** [comment]
> No, this doesn't change anything about the calibration. The only major thing that has been changed is TransformSettings, which only gets applied to the position of the PDF. TransformSettings does get loaded from local storage, but from my understanding my modification shouldn't cause an error when migrating.

Ok, great! I haven't really delved into the positioning or transformation code all that much, only enough to do simple things. So I appreciate the clarification on this.

> Edit: I'll test this just to be safe.

Appreciate it! I don't doubt you, but it doesn't hurt to be sure!

**Comment by j-huff** [comment]
Something to note: transformSettings is a dependency of draw, so now that it gets updated when dragging the PDF, the canvas will get re-rendered every frame of the drag mouse movement. This may be undesirable from a performance standpoint, as canvas renders can be pretty expensive. The reason transformSettings is a dependency of the draw useEffect is because it also stores the current color mode. It might be a good idea to separate the matrix and color mode to prevent unneeded re-renders.

In the future, we may want to add tools that use the canvas for drawing, and need re-rendered when the pdf is moved. I still think that modifying the matrix should only trigger canvas rerenders if the active tool absolutely needs it, so for now I'm going to sever that dependency and we'll cross that bridge when we get to it.

**Comment by hluedeke** [comment]
> Something to note: transformSettings is a dependency of draw, so now that it gets updated when dragging the PDF, the canvas will get re-rendered every frame of the drag mouse movement. This may be undesirable from a performance standpoint, as canvas renders can be pretty expensive. The reason transformSettings is a dependency of the draw useEffect is because it also stores the current color mode. It might be a good idea to separate the matrix and color mode to prevent unneeded re-renders.

Yeah, let's get rid of the dependency if it makes sense to do so. Preventing unnecessary re-renders is great! You can also make children of transformSettings the actual dependency (eg. transformSettings.color), instead of the whole transformSettings object. This might be the way to go if it doesn't otherwise make sense to break those up.

> In the future, we may want to add tools that use the canvas for drawing, and need re-rendered when the pdf is moved. I still think that modifying the matrix should only trigger canvas rerenders if the active tool absolutely needs it, so for now I'm going to sever that dependency and we'll cross that bridge when we get to it.

In that case, wouldn't we add the tool's state as a dependency in lieu of the actual matrix? You certainly wouldn't want both if they are linked. I'd say if you can remove extra dependencies and maintain current functionality, go for it.

**Comment by j-huff** [comment]
To me, it made sense to just go ahead and separate transformSettings from displaySettings, and remove transformSettings as a dependency. I also combined the overlayMode with displaySettings, and am now storing overlayMode in localStorage with the other displaySettings.

**Comment by j-huff** [comment]
> I just took a peek - do we need a whole object for TransformSettings now that it only has the matrix as the child? Is there a reason to hold onto that structure anymore?

Right now there isn't a good reason. The only reason I can think of is if in the future if we *really* wanted to have some other transform that get's treated separately from the matrix, although I don't know what that would be.

**Comment by j-huff** [comment]
Ah, I goofed it when. Reflections are back to being weird.

**Comment by j-huff** [comment]
Okay, doubled checked that calibration doesn't change on migration and it's fine. This branch should be good to go.

**Comment by courtneypattison** [comment]
That centre screen rotation is so much better. Such a good idea @hluedeke.

I didn't realize how much the recenter being off centre bothered me until this PR. It's so much nicer now! Thank you @j-huff!

**Pull request merged**
